# Generated by Django 6.0.3 on 2026-03-20 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GapAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('critical_gap', 'Critical Gap'), ('high_gap', 'High Gap'), ('ready_to_scale', 'Ready to Scale')], max_length=20)),
                ('learners_ready', models.IntegerField(default=0)),
                ('learners_placed', models.IntegerField(default=0)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('nqf_level', models.CharField(max_length=10)),
                ('qualification', models.CharField(max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('placed', 'Placed'), ('training', 'Training')], default='searching', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('learnership', 'Learnership'), ('internship', 'Internship'), ('job', 'Job')], max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('nqf_required', models.IntegerField()),
                ('skills_required', models.JSONField(default=list)),
                ('stipend', models.IntegerField(blank=True, null=True)),
                ('spots_available', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('filled', 'Filled')], default='open', max_length=20)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_type', models.CharField(choices=[('employer', 'Employer'), ('institution', 'Institution'), ('incubator', 'Incubator'), ('seta', 'SETA')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('use_case', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('institution_type', models.CharField(blank=True, choices=[('university', 'University'), ('tvet', 'TVET'), ('training_body', 'Training Body')], max_length=20, null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Learner', 'Learner'), ('Employer', 'Employer'), ('Institution', 'Institution'), ('Incubator', 'Incubator'), ('SETA', 'SETA')], max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.IntegerField()),
                ('ai_reason', models.TextField()),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learnerprofile')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opportunity')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('channel', models.CharField(choices=[('app', 'App'), ('ussd', 'USSD')], default='app', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.learnerprofile')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opportunity')),
            ],
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.organisationprofile'),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='core.user'),
        ),
        migrations.AddField(
            model_name='organisationprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_orgs', to='core.user'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to='core.user'),
        ),
    ]
